In [2]:
import os
os.chdir(r"G:\PycharmProjects\names-demo")

In [28]:
import pandas as pd
import os
import polars as pl
# folder containing your files
folder_path = "data/raw/names-usa/namesbystate"

# list all files (adjust extension if needed)
files = [f for f in os.listdir(folder_path) if f.endswith(".TXT")]

df_list = []

for file in files:
    file_path = os.path.join(folder_path, file)
    df = pd.read_csv(file_path,header=None,names=["province", "gender", "year", "name", "count"])
    df_list.append(df)

# combine all files into one dataframe
df = pd.concat(df_list, ignore_index=True)
df.head()

  province gender  year      name  count
0       AK      F  1910      Mary     14
1       AK      F  1910     Annie     12
2       AK      F  1910      Anna     10
3       AK      F  1910  Margaret      8
4       AK      F  1910     Helen      7

In [29]:
state_map = {
    'AK': 'Alaska', 'AL': 'Alabama', 'AR': 'Arkansas', 'AZ': 'Arizona',
    'CA': 'California', 'CO': 'Colorado', 'CT': 'Connecticut',
    'DC': 'District of Columbia', 'DE': 'Delaware', 'FL': 'Florida',
    'GA': 'Georgia', 'HI': 'Hawaii', 'IA': 'Iowa', 'ID': 'Idaho',
    'IL': 'Illinois', 'IN': 'Indiana', 'KS': 'Kansas', 'KY': 'Kentucky',
    'LA': 'Louisiana', 'MA': 'Massachusetts', 'MD': 'Maryland',
    'ME': 'Maine', 'MI': 'Michigan', 'MN': 'Minnesota',
    'MO': 'Missouri', 'MS': 'Mississippi', 'MT': 'Montana',
    'NC': 'North Carolina', 'ND': 'North Dakota', 'NE': 'Nebraska',
    'NH': 'New Hampshire', 'NJ': 'New Jersey', 'NM': 'New Mexico',
    'NV': 'Nevada', 'NY': 'New York', 'OH': 'Ohio', 'OK': 'Oklahoma',
    'OR': 'Oregon', 'PA': 'Pennsylvania', 'RI': 'Rhode Island',
    'SC': 'South Carolina', 'SD': 'South Dakota', 'TN': 'Tennessee',
    'TX': 'Texas', 'UT': 'Utah', 'VA': 'Virginia', 'VT': 'Vermont',
    'WA': 'Washington', 'WI': 'Wisconsin', 'WV': 'West Virginia',
    'WY': 'Wyoming'
}
df["province"] = df["province"].map(state_map)
# 'sex' sütunundaki değerleri yeni değerlerle eşleyelim
df.head()

  province gender  year      name  count
0   Alaska      F  1910      Mary     14
1   Alaska      F  1910     Annie     12
2   Alaska      F  1910      Anna     10
3   Alaska      F  1910  Margaret      8
4   Alaska      F  1910     Helen      7

In [30]:
df['gender'] = df['gender'].map({'F': 'female', 'M': 'male'})
df['total_count'] = df.groupby(['gender', 'year'])['count'].transform('sum')
df.head()

  province  gender  year      name  count  total_count
0   Alaska  female  1910      Mary     14       352089
1   Alaska  female  1910     Annie     12       352089
2   Alaska  female  1910      Anna     10       352089
3   Alaska  female  1910  Margaret      8       352089
4   Alaska  female  1910     Helen      7       352089

In [41]:
df[(df["year"]==2024) & (df["gender"]=="female")].tail()

        province  gender  year      name  count  total_count
6585945  Wyoming  female  2024    Quincy      5      1306118
6585946  Wyoming  female  2024    Sawyer      5      1306118
6585947  Wyoming  female  2024  Scarlett      5      1306118
6585948  Wyoming  female  2024       Zoe      5      1306118
6585949  Wyoming  female  2024      Zoey      5      1306118

In [8]:
# Save to Parquet
df.to_parquet("data/preprocessed/usa/names_usa_states.parquet", engine="pyarrow", index=False)

In [9]:
import polars as pl
df = pl.read_parquet("data/preprocessed/usa/names_usa_states.parquet")
df.head()

shape: (5, 6)
┌───────┬────────┬──────┬──────────┬───────────┬────────────┐
│ state ┆ gender ┆ year ┆ name     ┆ frequency ┆ state_name │
│ ---   ┆ ---    ┆ ---  ┆ ---      ┆ ---       ┆ ---        │
│ str   ┆ str    ┆ i64  ┆ str      ┆ i64       ┆ str        │
╞═══════╪════════╪══════╪══════════╪═══════════╪════════════╡
│ AK    ┆ F      ┆ 1910 ┆ Mary     ┆ 14        ┆ Alaska     │
│ AK    ┆ F      ┆ 1910 ┆ Annie    ┆ 12        ┆ Alaska     │
│ AK    ┆ F      ┆ 1910 ┆ Anna     ┆ 10        ┆ Alaska     │
│ AK    ┆ F      ┆ 1910 ┆ Margaret ┆ 8         ┆ Alaska     │
│ AK    ┆ F      ┆ 1910 ┆ Helen    ┆ 7         ┆ Alaska     │
└───────┴────────┴──────┴──────────┴───────────┴────────────┘